#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/sites.sh
source "${SCRIPT_DIR}/lib/sites.sh"
clodsite_init_site_dir

if [ ! -f "${SITE_DIR}/build-plan.yaml" ]; then
  echo "Error: ${SITE_DIR}/build-plan.yaml not found."
  exit 1
fi

STYLE=$(node "${SCRIPT_DIR}/lib/build-plan.mjs" \
  "${SITE_DIR}/build-plan.yaml" style)
THEME_FILE="scaffold/src/css/themes/${STYLE}.css"

if [ ! -f "$THEME_FILE" ]; then
  echo "Error: Theme file not found: $THEME_FILE"
  echo "Valid styles: minimal, professional, bold"
  exit 1
fi

echo "✓ Theme: $STYLE ($THEME_FILE exists)"

# Concatenate all components/*/component.css into scaffold/src/css/components.css
# (overwritten on every build; gitignored).
COMPONENTS_DIR="${COMPONENTS_DIR:-components}"
OUT="scaffold/src/css/components.css"
{
  echo "/* Generated by scripts/apply-theme.sh — do not edit by hand. */"
  for css in "${COMPONENTS_DIR}"/*/component.css; do
    [ -f "$css" ] || continue
    name=$(basename "$(dirname "$css")")
    echo ""
    echo "/* --- ${name} --- */"
    cat "$css"
  done
} > "$OUT"
echo "✓ ${OUT} written ($(ls -1 "${COMPONENTS_DIR}"/*/component.css 2>/dev/null | wc -l | tr -d ' ') component(s))"
