#!/usr/bin/env bash
set -euo pipefail

COMPONENTS_DIR="${COMPONENTS_DIR:-components}"

if [ ! -d "$COMPONENTS_DIR" ]; then
  echo "Error: $COMPONENTS_DIR/ not found"
  exit 1
fi

node -e "
const fs = require('fs');
const path = require('path');
const dir = '${COMPONENTS_DIR}';
const names = fs.readdirSync(dir)
  .filter(n => fs.statSync(path.join(dir, n)).isDirectory())
  .sort();

let out = '# Component Catalog\n\n';
out += '> Generated by scripts/generate-catalog-md.sh — do not edit by hand.\n';
out += '> The /plan LLM reads this file to learn what components exist.\n\n';
out += 'A page in build-plan.yaml is a list of components stacked vertically.\n';
out += 'Each component has a \`type\` field naming one of the entries below.\n\n';
out += '---\n\n';

for (const name of names) {
  const schemaPath = path.join(dir, name, 'schema.json');
  if (!fs.existsSync(schemaPath)) continue;
  const schema = JSON.parse(fs.readFileSync(schemaPath, 'utf8'));
  out += '## ' + name + '\n\n';
  out += (schema.description || '_no description_') + '\n\n';

  out += '**Required fields:**\n\n';
  const req = schema.required || {};
  if (Object.keys(req).length === 0) {
    out += '_(none)_\n\n';
  } else {
    for (const [field, type] of Object.entries(req)) {
      out += '- \`' + field + '\` (' + type + ')\n';
    }
    out += '\n';
  }

  out += '**Optional fields:**\n\n';
  const opt = schema.optional || {};
  if (Object.keys(opt).length === 0) {
    out += '_(none)_\n\n';
  } else {
    for (const [field, type] of Object.entries(opt)) {
      out += '- \`' + field + '\` (' + type + ')\n';
    }
    out += '\n';
  }
}

process.stdout.write(out);
"
