#!/usr/bin/env bash
set -euo pipefail

COMPONENTS_DIR="${COMPONENTS_DIR:-components}"

if [ ! -d "$COMPONENTS_DIR" ]; then
  echo "Error: $COMPONENTS_DIR/ not found"
  exit 1
fi

node -e "
const fs = require('fs');
const path = require('path');
const dir = '${COMPONENTS_DIR}';
const names = fs.readdirSync(dir)
  .filter(n => fs.statSync(path.join(dir, n)).isDirectory())
  .sort();

let out = '# Component Catalog\n\n';
out += '> Generated by scripts/generate-catalog-md.sh — do not edit by hand.\n';
out += '> The /plan LLM reads this file to learn what components exist.\n\n';
out += 'A page in build-plan.yaml is a list of components stacked vertically.\n';
out += 'Each component has a \`type\` field naming one of the entries below.\n\n';
out += '---\n\n';

function describeDescriptor(descriptor) {
  if (typeof descriptor === 'string') return descriptor;
  let description = descriptor.type;
  if (descriptor.non_empty === true) description = 'non-empty ' + description;
  if (Array.isArray(descriptor.enum))
    description += '; one of: ' + descriptor.enum.join(', ');
  return description;
}

function collectFields(fields, prefix, requiredOut, optionalOut, isRequired) {
  for (const [field, descriptor] of Object.entries(fields || {})) {
    const fieldPath = prefix ? prefix + '.' + field : field;
    const target = isRequired ? requiredOut : optionalOut;
    target.push([fieldPath, describeDescriptor(descriptor)]);

    if (descriptor && typeof descriptor === 'object' && descriptor.type === 'object') {
      collectFields(descriptor.required || {}, fieldPath, requiredOut, optionalOut, true);
      collectFields(descriptor.optional || {}, fieldPath, requiredOut, optionalOut, false);
    }
  }
}

function renderFieldList(entries) {
  if (entries.length === 0) return '_(none)_\n\n';
  return entries.map(([field, description]) =>
    '- \`' + field + '\` (' + description + ')'
  ).join('\n') + '\n\n';
}

for (const name of names) {
  const schemaPath = path.join(dir, name, 'schema.json');
  if (!fs.existsSync(schemaPath)) continue;
  const schema = JSON.parse(fs.readFileSync(schemaPath, 'utf8'));
  out += '## ' + name + '\n\n';
  out += (schema.description || '_no description_') + '\n\n';

  out += '**Required fields:**\n\n';
  const requiredFields = [];
  const optionalFields = [];
  collectFields(schema.required || {}, '', requiredFields, optionalFields, true);
  collectFields(schema.optional || {}, '', requiredFields, optionalFields, false);
  out += renderFieldList(requiredFields);

  out += '**Optional fields:**\n\n';
  out += renderFieldList(optionalFields);

  if (schema.example) {
    out += '**Example:**\n\n';
    out += '\`\`\`yaml\n' + schema.example.trimEnd() + '\n\`\`\`\n\n';
  }
}

process.stdout.write(out);
"
