#!/usr/bin/env bash
set -euo pipefail

DRAFT="scripts/.spec-draft.json"

if [ ! -f "$DRAFT" ]; then
  echo "Error: $DRAFT not found."
  echo "This script is called by the /interview command after Claude writes the spec JSON."
  exit 1
fi

# Validate it's parseable JSON
if ! node -e "JSON.parse(require('fs').readFileSync('$DRAFT', 'utf8'))" 2>/dev/null; then
  echo "Error: $DRAFT is not valid JSON. Check Claude's output."
  exit 1
fi

# Save as site-spec.json
cp "$DRAFT" site-spec.json

# Generate human-readable site-spec.md
node -e "
const spec = JSON.parse(require('fs').readFileSync('site-spec.json', 'utf8'));
const lines = [
  '# Site Spec',
  '',
  '_Generated by /interview. Do not edit manually._',
  '_To update: re-run /interview (or /modify when available)._',
  '',
  '\`\`\`json',
  JSON.stringify(spec, null, 2),
  '\`\`\`',
  ''
];
require('fs').writeFileSync('site-spec.md', lines.join('\n'));
"

# Clean up draft
rm "$DRAFT"

echo "✓ Spec written to site-spec.json and site-spec.md"
echo ""
echo "Next step: run /plan"
